module.exports = {
  algorithms: [
    {
      type: "autogenerated",
      dirName: "coding-test",
    },
  ],
  computerScience: [
    {
      type: "autogenerated",
      dirName: "cs",
    },
  ],
  onlineLecture: [
    {
      type: "autogenerated",
      dirName: "online-lecture",
    },
  ],
};
